# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 15:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gcfnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=45, unique=True, verbose_name='PO')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
                ('model', models.CharField(max_length=45, verbose_name='Model')),
                ('family', models.CharField(max_length=45, verbose_name='Platform')),
                ('level', models.CharField(max_length=45, verbose_name='Level')),
                ('region', models.CharField(max_length=45, verbose_name='Region')),
                ('ctomod', models.CharField(max_length=45, verbose_name='Channel')),
                ('dest', models.CharField(max_length=45, verbose_name='Destination')),
                ('OSP', models.CharField(max_length=45)),
                ('OSD', models.CharField(max_length=45)),
                ('OSV', models.CharField(max_length=45)),
                ('muiflag', models.BooleanField(default=False)),
                ('cfiflag', models.BooleanField(default=False)),
                ('siaccount', models.CharField(blank=True, max_length=45, null=True, verbose_name='CFI Account')),
                ('mod', models.TextField(verbose_name='MOD Content')),
                ('sdr', models.TextField(verbose_name='SDR Content')),
                ('filepath', models.CharField(max_length=100, verbose_name='File Path')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
            ],
            options={
                'verbose_name': 'GCF Record',
                'verbose_name_plural': 'GCF Record',
            },
        ),
    ]
