# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 15:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cfinote',
            fields=[
                ('account', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Account')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
                ('last_modify', models.DateTimeField(verbose_name='Last Modify Time')),
                ('last_access', models.DateTimeField(verbose_name='Last Access Time')),
                ('ExistFlag', models.BooleanField(default=False)),
                ('OrderFlag', models.BooleanField(default=False)),
                ('size', models.BigIntegerField(default=0, verbose_name='Size')),
            ],
            options={
                'verbose_name': 'CFI Account',
                'verbose_name_plural': 'CFI Account',
            },
        ),
        migrations.CreateModel(
            name='patch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('start_mail', models.CharField(choices=[('y', 'Send'), ('n', 'Not send')], default='n', max_length=2)),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('end_mail', models.CharField(choices=[('y', 'Send'), ('n', 'Not send')], default='n', max_length=2)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('notice', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description')),
                ('size', models.BigIntegerField(default=0, verbose_name='Size')),
            ],
            options={
                'verbose_name': 'Deviation',
                'verbose_name_plural': 'Deviation',
            },
        ),
    ]
