# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='name')),
                ('model', models.CharField(max_length=20, verbose_name='SysID')),
                ('lob', models.CharField(max_length=20, verbose_name='LOB')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
                ('pebit', models.CharField(choices=[('64', '64'), ('32', '32')], default='64', max_length=2, verbose_name='PE')),
                ('product', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model Name')),
                ('phnum', models.CharField(blank=True, max_length=20, null=True, verbose_name='PH#')),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platform',
            },
        ),
    ]
